parameters:
#    vectorface_backlog.example.class: Vectorface\BacklogBundle\Example

services:
    redishelper:
        class: Vectorface\BacklogBundle\RedisHelper
        calls:
            - [setContainer, [@service_container]]
