parameters:
#    vectorface_backlog.example.class: Vectorface\BacklogBundle\Example

services:
    redisservice:
        class: Vectorface\BacklogBundle\Service\RedisService
        calls:
            - [setContainer, [@service_container]]
    fogbugzservice:
        class: Vectorface\BacklogBundle\Service\FogbugzService
        arguments: ["%fogbugz%", "@RedisService"]
        calls:
            - [setContainer, [@service_container]]
    Vectorface.twig.fogbugz_extension:
        class: Vectorface\BacklogBundle\Twig\Extension\FogbugzExtension
        tags:
            - { name: twig.extension }
        arguments: ["%fogbugz%"]